In [1]:
#Groupby 
# split data into groups bas on some criteria 
# Applys a function to groups independently 
# Conbines the result into a dataframes

In [2]:
#The Groupby Object 

import pandas as pd

In [3]:
oo=pd.read_csv("athlete_events.csv")

In [4]:
oo.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [5]:
oo.groupby("Year")

In [6]:
type(oo.groupby("Year"))

pandas.core.groupby.generic.DataFrameGroupBy

In [7]:
list(oo.groupby("Year"))

[(1896,
              ID                                Name Sex   Age  Height  Weight  \
  3079      1724              Aristidis Akratopoulos   M   NaN     NaN     NaN
  3080      1724              Aristidis Akratopoulos   M   NaN     NaN     NaN
  3081      1725  Konstantinos "Kostas" Akratopoulos   M   NaN     NaN     NaN
  3082      1725  Konstantinos "Kostas" Akratopoulos   M   NaN     NaN     NaN
  7348      4113                  Anastasios Andreou   M   NaN     NaN     NaN
  ...        ...                                 ...  ..   ...     ...     ...
  270473  135285                     Khristos Zoumis   M   NaN     NaN     NaN
  270914  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN
  270915  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN
  270916  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN
  270917  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN

                 Team  NOC        Games  Year  Season    City       Sport  \
  3079         Greece  GRE  1896 Summer  1896  Summer  Athina      Tennis
  3080       Greece-3  GRE  1896 Summer  1896  Summer  Athina      Tennis
  3081         Greece  GRE  1896 Summer  1896  Summer  Athina      Tennis
  3082       Greece-3  GRE  1896 Summer  1896  Summer  Athina      Tennis
  7348         Greece  GRE  1896 Summer  1896  Summer  Athina   Athletics
  ...             ...  ...          ...   ...     ...     ...         ...
  270473       Greece  GRE  1896 Summer  1896  Summer  Athina   Athletics
  270914  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics
  270915  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics
  270916  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics
  270917  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics

                                       Event   Medal
  3079                  Tennis Men's Singles     NaN
  3080                  Tennis Men's Doubles     NaN
  3081                  Tennis Men's Singles     NaN
  3082                  Tennis Men's Doubles     NaN
  7348    Athletics Men's 110 metres Hurdles     NaN
  ...                                    ...     ...
  270473         Athletics Men's Triple Jump     NaN
  270914        Gymnastics Men's Horse Vault  Silver
  270915      Gymnastics Men's Parallel Bars  Silver
  270916     Gymnastics Men's Horizontal Bar     NaN
  270917    Gymnastics Men's Pommelled Horse    Gold

  [380 rows x 15 columns]),
 (1900,
              ID                                 Name Sex   Age  Height  Weight  \
  3            4                 Edgar Lindenau Aabye   M  34.0     NaN     NaN
  261        133                            Franz Abb   M   NaN     NaN     NaN
  283        150        Margaret Ives Abbott (-Dunne)   F  23.0     NaN     NaN
  284        151  Mary Perkins Ives Abbott (Perkins-)   F  42.0     NaN     NaN
  710        404          Louis Grenville "Lou" Abell   M  15.0     NaN     NaN
  ...        ...                                  ...  ..   ...     ...     ...
  263255  131733                William Hayden Wright   M   NaN     NaN     NaN
  266979  133574                           Henri Yvon   M   NaN     NaN     NaN
  266980  133574                           Henri Yvon   M   NaN     NaN     NaN
  267457  133807           Pyotr Antonovich Zakovorot   M   NaN     NaN     NaN
  268232  134198           Walter John "Jack" Zealley   M   NaN     NaN     NaN

                           Team  NOC        Games  Year  Season   City  \
  3              Denmark/Sweden  DEN  1900 Summer  1900  Summer  Paris
  261                   Germany  GER  1900 Summer  1900  Summer  Paris
  283             United States  USA  1900 Summer  1900  Summer  Paris
  284             United States  USA  1900 Summer  1900  Summer  Paris
  710          Vesper Boat Club  USA  1900 Summer  1900  Summer  Paris
  ...                       ...  ...          ...   ...     ...    ...
  263255  A North American Team  USA  1900 Summer  1900  Summer  Paris
  266979                 France  FRA  1900 Summer  1900  Summer  Paris
  266980                 France  FRA  1900 Summer  1900  Summer  Paris
  267457                 Russia  RUS  1900 Summer  1900  Summer  Paris
  268232          Upton Park FC  GBR  1900 Summer  1900  Summer  Paris

               Sport                                     Event   Medal
  3       Tug-Of-War               Tug-Of-War Men's Tug-Of-War    Gold
  261     Gymnastics    Gymnastics Men's Individual All-Around     NaN
  283           Golf                   Golf Women's Individual    Gold
  284           Golf                   Golf Women's Individual     NaN
  710         Rowing                 Rowing Men's Coxed Eights    Gold
  ...            ...                                       ...     ...
  263255        Polo                           Polo Men's Polo  Bronze
  266979     Fencing   Fencing Men's Foil, Masters, Individual     NaN
  266980     Fencing   Fencing Men's epee, Masters, Individual     NaN
  267457     Fencing  Fencing Men's Sabre, Masters, Individual     NaN
  268232    Football                   Football Men's Football    Gold

  [1936 rows x 15 columns]),
 (1904,
              ID                         Name Sex   Age  Height  Weight  \
  711        404  Louis Grenville "Lou" Abell   M  19.0     NaN     NaN
  1449       806     Bartlett S. "Bart" Adams   M  38.0     NaN     NaN
  1458       813           Edgar Holmes Adams   M  36.0     NaN     NaN
  1459       813           Edgar Holmes Adams   M  36.0     NaN     NaN
  1460       813           Edgar Holmes Adams   M  36.0     NaN     NaN
  ...        ...                          ...  ..   ...     ...     ...
  267010  133588                Wilhelm Zabel   M   NaN     NaN     NaN
  267089  133620              Georg Zacharias   M  20.0     NaN     NaN
  267090  133620              Georg Zacharias   M  20.0     NaN     NaN
  268337  134263      Khristos D. Zekhouritis   M   NaN     NaN     NaN
  270058  135103    Albert Conrad "Al" Zirkel   M  19.0     NaN     NaN

                      Team  NOC        Games  Year  Season       City  \
  711     Vesper Boat Club  USA  1904 Summer  1904  Summer  St. Louis
  1449       United States  USA  1904 Summer  1904  Summer  St. Louis
  1458       United States  USA  1904 Summer  1904  Summer  St. Louis
  1459       United States  USA  1904 Summer  1904  Summer  St. Louis
  1460       United States  USA  1904 Summer  1904  Summer  St. Louis
  ...                  ...  ...          ...   ...     ...        ...
  267010     United States  USA  1904 Summer  1904  Summer  St. Louis
  267089           Germany  GER  1904 Summer  1904  Summer  St. Louis
  267090           Germany  GER  1904 Summer  1904  Summer  St. Louis
  268337            Greece  GRE  1904 Summer  1904  Summer  St. Louis
  270058     United States  USA  1904 Summer  1904  Summer  St. Louis

               Sport                                              Event   Medal
  711         Rowing                          Rowing Men's Coxed Eights    Gold
  1449          Golf                              Golf Men's Individual     NaN
  1458      Swimming                  Swimming Men's 220 yard Freestyle     NaN
  1459      Swimming                  Swimming Men's 880 yard Freestyle     NaN
  1460      Swimming                  Swimming Men's One Mile Freestyle     NaN
  ...            ...                                                ...     ...
  267010  Gymnastics  Gymnastics Men's Individual All-Around, Appara...     NaN
  267089    Swimming                 Swimming Men's 100 Yard Backstroke  Bronze
  267090    Swimming               Swimming Men's 440 Yard Breaststroke    Gold
  268337   Athletics                           Athletics Men's Marathon     NaN
  270058   Wrestling             Wrestling Men's Lightweight, Freestyle  Bronze

  [1301 rows x 15 columns]),
 (1906,
              ID                     Name Sex   Age  Height  Weight  \
  268        139   George "Ioannis" Abbot   M   NaN     NaN     NaN
  887        508         Bernhard Abraham   M   NaN     NaN     NaN
  918        520  Sidney Solomon Abrahams   M  21.0     NaN     NaN
  919        520  Sidney Solomon Abrahams   M  21.0     NaN     NaN
  2170      1208          Ioannis Agrimis   M   NaN     NaN     NaN
  ...        ...                      ...  ..   ...     ...     ...
  270355  135239          Khristos Zorbas   M   NaN     NaN     NaN
  270356  135239          Khristos Zorbas   M   NaN     NaN     NaN
  270357  135239          Khristos Zorbas   M   NaN     NaN     NaN
  270358  135239          Khristos Zorbas   M   NaN     NaN     NaN
  270895  135474     Albert Hermann Zrner   M  16.0     NaN     NaN

                                                     Team  NOC        Games  \
  268                                       Thessalonki-1  GRE  1906 Summer
  887                                             Germany  GER  1906 Summer
  918                                       Great Britain  GBR  1906 Summer
  919                                       Great Britain  GBR  1906 Summer
  2170    Large boat, Central Naval Prep School "Poros"-1  GRE  1906 Summer
  ...                                                 ...  ...          ...
  270355                                           Greece  GRE  1906 Summer
  270356                                           Greece  GRE  1906 Summer
  270357                                           Greece  GRE  1906 Summer
  270358                                           Greece  GRE  1906 Summer
  270895                                          Germany  GER  1906 Summer

          Year  Season    City       Sport  \
  268     1906  Summer  Athina    Football
  887     1906  Summer  Athina  Gymnastics
  918     1906  Summer  Athina   Athletics
  919     1906  Summer  Athina   Athletics
  2170    1906  Summer  Athina      Rowing
  ...      ...     ...     ...         ...
  270355  1906  Summer  Athina     Fencing
  270356  1906  Summer  Athina     Fencing
  270357  1906  Summer  Athina     Fencing
  270358  1906  Summer  Athina     Fencing
  270895  1906  Summer  Athina      Diving

                                                Event   Medal
  268                         Football Men's Football  Bronze
  887                Gymnastics Men's Team All-Around     NaN
  918                      Athletics Men's 100 metres     NaN
  919                       Athletics Men's Long Jump     NaN
  2170         Rowing Men's 17-Man Naval Rowing Boats    Gold
  ...                                             ...     ...
  270355                     Fencing Men's epee, Team     NaN
  270356              Fencing Men's Sabre, Individual     NaN
  270357  Fencing Men's Sabre, Individual, Three Hits     NaN
  270358                    Fencing Men's Sabre, Team  Silver
  270895                        Diving Men's Platform     NaN

  [1733 rows x 15 columns]),
 (1908,
              ID                    Name Sex   Age  Height  Weight  \
  1149       635         Alfredo Accorsi   M  27.0     NaN     NaN
  1354       767  Johannes "Johann" Adam   M   NaN     NaN     NaN
  1355       767  Johannes "Johann" Adam   M   NaN     NaN     NaN
  1463       814            Edward Adams   M   NaN     NaN     NaN
  1505       836             Platt Adams   M  23.0   188.0    78.0
  ...        ...                     ...  ..   ...     ...     ...
  270474  135286      Kharalambos Zouras   M  23.0     NaN     NaN
  270475  135286      Kharalambos Zouras   M  23.0     NaN     NaN
  270750  135406           Bla Zulawszky   M  38.0     NaN     NaN
  270751  135406           Bla Zulawszky   M  38.0     NaN     NaN
  270896  135474    Albert Hermann Zrner   M  18.0     NaN     NaN

                   Team  NOC        Games  Year  Season    City       Sport  \
  1149            Italy  ITA  1908 Summer  1908  Summer  London  Gymnastics
  1354          Germany  GER  1908 Summer  1908  Summer  London     Fencing
  1355          Germany  GER  1908 Summer  1908  Summer  London     Fencing
  1463    Great Britain  GBR  1908 Summer  1908  Summer  London      Boxing
  1505    United States  USA  1908 Summer  1908  Summer  London   Athletics
  ...               ...  ...          ...   ...     ...     ...         ...
  270474         Greece  GRE  1908 Summer  1908  Summer  London   Athletics
  270475         Greece  GRE  1908 Summer  1908  Summer  London   Athletics
  270750        Hungary  HUN  1908 Summer  1908  Summer  London     Fencing
  270751        Hungary  HUN  1908 Summer  1908  Summer  London     Fencing
  270896        Germany  GER  1908 Summer  1908  Summer  London      Diving

                                             Event   Medal
  1149            Gymnastics Men's Team All-Around     NaN
  1354              Fencing Men's epee, Individual     NaN
  1355             Fencing Men's Sabre, Individual     NaN
  1463                  Boxing Men's Featherweight     NaN
  1505          Athletics Men's Standing High Jump     NaN
  ...                                          ...     ...
  270474             Athletics Men's Javelin Throw     NaN
  270475  Athletics Men's Javelin Throw, Freestyle     NaN
  270750            Fencing Men's epee, Individual     NaN
  270751           Fencing Men's Sabre, Individual  Silver
  270896                  Diving Men's Springboard    Gold

  [3101 rows x 15 columns]),
 (1912,
              ID                  Name Sex   Age  Height  Weight     Team  NOC  \
  35          15  Arvo Ossian Aaltonen   M  22.0     NaN     NaN  Finland  FIN
  36          15  Arvo Ossian Aaltonen   M  22.0     NaN     NaN  Finland  FIN
  95          32  Olav Augunson Aarnes   M  23.0     NaN     NaN   Norway  NOR
  107         39    Lars Thorlaksn Aas   M  33.0     NaN     NaN   Norway  NOR
  108         39    Lars Thorlaksn Aas   M  33.0     NaN     NaN   Norway  NOR
  ...        ...                   ...  ..   ...     ...     ...      ...  ...
  270752  135406         Bla Zulawszky   M  42.0     NaN     NaN  Hungary  HUN
  270753  135406         Bla Zulawszky   M  42.0     NaN     NaN  Hungary  HUN
  270897  135474  Albert Hermann Zrner   M  22.0     NaN     NaN  Germany  GER
  270898  135474  Albert Hermann Zrner   M  22.0     NaN     NaN  Germany  GER
  270899  135474  Albert Hermann Zrner   M  22.0     NaN     NaN  Germany  GER

                Games  Year  Season       City      Sport  \
  35      1912 Summer  1912  Summer  Stockholm   Swimming
  36      1912 Summer  1912  Summer  Stockholm   Swimming
  95      1912 Summer  1912  Summer  Stockholm  Athletics
  107     1912 Summer  1912  Summer  Stockholm    Fencing
  108     1912 Summer  1912  Summer  Stockholm    Fencing
  ...             ...   ...     ...        ...        ...
  270752  1912 Summer  1912  Summer  Stockholm    Fencing
  270753  1912 Summer  1912  Summer  Stockholm    Fencing
  270897  1912 Summer  1912  Summer  Stockholm     Diving
  270898  1912 Summer  1912  Summer  Stockholm     Diving
  270899  1912 Summer  1912  Summer  Stockholm     Diving

                                           Event   Medal
  35      Swimming Men's 200 metres Breaststroke     NaN
  36      Swimming Men's 400 metres Breaststroke     NaN
  95                   Athletics Men's High Jump     NaN
  107             Fencing Men's Foil, Individual     NaN
  108             Fencing Men's epee, Individual     NaN
  ...                                        ...     ...
  270752          Fencing Men's Foil, Individual     NaN
  270753         Fencing Men's Sabre, Individual     NaN
  270897                Diving Men's Springboard     NaN
  270898                   Diving Men's Platform  Silver
  270899                 Diving Men's Plain High     NaN

  [4040 rows x 15 columns]),
 (1920,
              ID                  Name Sex   Age  Height  Weight         Team  \
  2            3   Gunnar Nielsen Aaby   M  24.0     NaN     NaN      Denmark
  37          15  Arvo Ossian Aaltonen   M  30.0     NaN     NaN      Finland
  38          15  Arvo Ossian Aaltonen   M  30.0     NaN     NaN      Finland
  86          25      Alf Lied Aanning   M  24.0     NaN     NaN       Norway
  106         38          Karl Jan Aas   M  20.0     NaN     NaN       Norway
  ...        ...                   ...  ..   ...     ...     ...          ...
  270672  135364        Vittorio Zucca   M  24.0     NaN     NaN        Italy
  270747  135405          Fritz Zulauf   M  27.0     NaN     NaN  Switzerland
  270748  135405          Fritz Zulauf   M  27.0     NaN     NaN  Switzerland
  270749  135405          Fritz Zulauf   M  27.0     NaN     NaN  Switzerland
  270843  135455       Vjekoslav upani   M  19.0     NaN     NaN   Yugoslavia

          NOC        Games  Year  Season       City       Sport  \
  2       DEN  1920 Summer  1920  Summer  Antwerpen    Football
  37      FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
  38      FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
  86      NOR  1920 Summer  1920  Summer  Antwerpen  Gymnastics
  106     NOR  1920 Summer  1920  Summer  Antwerpen  Gymnastics
  ...     ...          ...   ...     ...        ...         ...
  270672  ITA  1920 Summer  1920  Summer  Antwerpen   Athletics
  270747  SUI  1920 Summer  1920  Summer  Antwerpen    Shooting
  270748  SUI  1920 Summer  1920  Summer  Antwerpen    Shooting
  270749  SUI  1920 Summer  1920  Summer  Antwerpen    Shooting
  270843  YUG  1920 Summer  1920  Summer  Antwerpen    Football

                                                  Event   Medal
  2                             Football Men's Football     NaN
  37             Swimming Men's 200 metres Breaststroke  Bronze
  38             Swimming Men's 400 metres Breaststroke  Bronze
  86      Gymnastics Men's Team All-Around, Free System  Silver
  106     Gymnastics Men's Team All-Around, Free System  Silver
  ...                                               ...     ...
  270672           Athletics Men's 4 x 100 metres Relay     NaN
  270747           Shooting Men's Military Pistol, Team  Bronze
  270748    Shooting Men's Free Pistol, 50 metres, Team     NaN
  270749      Shooting Men's Military Pistol, 30 metres  Bronze
  270843                        Football Men's Football     NaN

  [4292 rows x 15 columns]),
 (1924,
              ID                   Name Sex   Age  Height  Weight  \
  39          15   Arvo Ossian Aaltonen   M  34.0     NaN     NaN
  132         47   Erling Rudolf Aastad   M  26.0   177.0    74.0
  152         58       Georgi Abadzhiev   M   NaN     NaN     NaN
  153         58       Georgi Abadzhiev   M   NaN     NaN     NaN
  181         79  Carlos Abarca Gonzlez   M  23.0     NaN     NaN
  ...        ...                    ...  ..   ...     ...     ...
  270673  135364         Vittorio Zucca   M  28.0     NaN     NaN
  270676  135366    Francesco Zucchetti   M  22.0     NaN     NaN
  270794  135427      Frank Thomas Zuna   M  31.0   175.0    69.0
  271010  135521          Anton Zwerina   M  23.0     NaN    66.0
  271038  135539  Marius Edmund Zwiller   M  18.0     NaN     NaN

                   Team  NOC        Games  Year  Season   City          Sport  \
  39            Finland  FIN  1924 Summer  1924  Summer  Paris       Swimming
  132            Norway  NOR  1924 Summer  1924  Summer  Paris      Athletics
  152          Bulgaria  BUL  1924 Summer  1924  Summer  Paris        Cycling
  153          Bulgaria  BUL  1924 Summer  1924  Summer  Paris        Cycling
  181             Chile  CHI  1924 Summer  1924  Summer  Paris         Boxing
  ...               ...  ...          ...   ...     ...    ...            ...
  270673          Italy  ITA  1924 Summer  1924  Summer  Paris      Athletics
  270676          Italy  ITA  1924 Summer  1924  Summer  Paris        Cycling
  270794  United States  USA  1924 Summer  1924  Summer  Paris      Athletics

In [8]:
#iterating through a group

In [9]:
for group_key,group_value in oo.groupby("Year"):
    print(group_key)
    print(group_value)

1896
            ID                                Name Sex   Age  Height  Weight  \
3079      1724              Aristidis Akratopoulos   M   NaN     NaN     NaN
3080      1724              Aristidis Akratopoulos   M   NaN     NaN     NaN
3081      1725  Konstantinos "Kostas" Akratopoulos   M   NaN     NaN     NaN
3082      1725  Konstantinos "Kostas" Akratopoulos   M   NaN     NaN     NaN
7348      4113                  Anastasios Andreou   M   NaN     NaN     NaN
...        ...                                 ...  ..   ...     ...     ...
270473  135285                     Khristos Zoumis   M   NaN     NaN     NaN
270914  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN
270915  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN
270916  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN
270917  135481         Jules Alexis "Louis" Zutter   M  30.0     NaN     NaN

               Team  NOC        Games  Year  Season    City       Sport  \
3079         Greece  GRE  1896 Summer  1896  Summer  Athina      Tennis
3080       Greece-3  GRE  1896 Summer  1896  Summer  Athina      Tennis
3081         Greece  GRE  1896 Summer  1896  Summer  Athina      Tennis
3082       Greece-3  GRE  1896 Summer  1896  Summer  Athina      Tennis
7348         Greece  GRE  1896 Summer  1896  Summer  Athina   Athletics
...             ...  ...          ...   ...     ...     ...         ...
270473       Greece  GRE  1896 Summer  1896  Summer  Athina   Athletics
270914  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics
270915  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics
270916  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics
270917  Switzerland  SUI  1896 Summer  1896  Summer  Athina  Gymnastics

                                     Event   Medal
3079                  Tennis Men's Singles     NaN
3080                  Tennis Men's Doubles     NaN
3081                  Tennis Men's Singles     NaN
3082                  Tennis Men's Doubles     NaN
7348    Athletics Men's 110 metres Hurdles     NaN
...                                    ...     ...
270473         Athletics Men's Triple Jump     NaN
270914        Gymnastics Men's Horse Vault  Silver
270915      Gymnastics Men's Parallel Bars  Silver
270916     Gymnastics Men's Horizontal Bar     NaN
270917    Gymnastics Men's Pommelled Horse    Gold

[380 rows x 15 columns]
1900
            ID                                 Name Sex   Age  Height  Weight  \
3            4                 Edgar Lindenau Aabye   M  34.0     NaN     NaN
261        133                            Franz Abb   M   NaN     NaN     NaN
283        150        Margaret Ives Abbott (-Dunne)   F  23.0     NaN     NaN
284        151  Mary Perkins Ives Abbott (Perkins-)   F  42.0     NaN     NaN
710        404          Louis Grenville "Lou" Abell   M  15.0     NaN     NaN
...        ...                                  ...  ..   ...     ...     ...
263255  131733                William Hayden Wright   M   NaN     NaN     NaN
266979  133574                           Henri Yvon   M   NaN     NaN     NaN
266980  133574                           Henri Yvon   M   NaN     NaN     NaN
267457  133807           Pyotr Antonovich Zakovorot   M   NaN     NaN     NaN
268232  134198           Walter John "Jack" Zealley   M   NaN     NaN     NaN

                         Team  NOC        Games  Year  Season   City  \
3              Denmark/Sweden  DEN  1900 Summer  1900  Summer  Paris
261                   Germany  GER  1900 Summer  1900  Summer  Paris
283             United States  USA  1900 Summer  1900  Summer  Paris
284             United States  USA  1900 Summer  1900  Summer  Paris
710          Vesper Boat Club  USA  1900 Summer  1900  Summer  Paris
...                       ...  ...          ...   ...     ...    ...
263255  A North American Team  USA  1900 Summer  1900  Summer  Paris
266979                 France  FRA  1900 Summer  1900  Summer  Paris
266980                 France  FRA  1900 Summer  1900  Summer  Paris
267457                 Russia  RUS  1900 Summer  1900  Summer  Paris
268232          Upton Park FC  GBR  1900 Summer  1900  Summer  Paris

             Sport                                     Event   Medal
3       Tug-Of-War               Tug-Of-War Men's Tug-Of-War    Gold
261     Gymnastics    Gymnastics Men's Individual All-Around     NaN
283           Golf                   Golf Women's Individual    Gold
284           Golf                   Golf Women's Individual     NaN
710         Rowing                 Rowing Men's Coxed Eights    Gold
...            ...                                       ...     ...
263255        Polo                           Polo Men's Polo  Bronze
266979     Fencing   Fencing Men's Foil, Masters, Individual     NaN
266980     Fencing   Fencing Men's epee, Masters, Individual     NaN
267457     Fencing  Fencing Men's Sabre, Masters, Individual     NaN
268232    Football                   Football Men's Football    Gold

[1936 rows x 15 columns]
1904
            ID                         Name Sex   Age  Height  Weight  \
711        404  Louis Grenville "Lou" Abell   M  19.0     NaN     NaN
1449       806     Bartlett S. "Bart" Adams   M  38.0     NaN     NaN
1458       813           Edgar Holmes Adams   M  36.0     NaN     NaN
1459       813           Edgar Holmes Adams   M  36.0     NaN     NaN
1460       813           Edgar Holmes Adams   M  36.0     NaN     NaN
...        ...                          ...  ..   ...     ...     ...
267010  133588                Wilhelm Zabel   M   NaN     NaN     NaN
267089  133620              Georg Zacharias   M  20.0     NaN     NaN
267090  133620              Georg Zacharias   M  20.0     NaN     NaN
268337  134263      Khristos D. Zekhouritis   M   NaN     NaN     NaN
270058  135103    Albert Conrad "Al" Zirkel   M  19.0     NaN     NaN

                    Team  NOC        Games  Year  Season       City  \
711     Vesper Boat Club  USA  1904 Summer  1904  Summer  St. Louis
1449       United States  USA  1904 Summer  1904  Summer  St. Louis
1458       United States  USA  1904 Summer  1904  Summer  St. Louis
1459       United States  USA  1904 Summer  1904  Summer  St. Louis
1460       United States  USA  1904 Summer  1904  Summer  St. Louis
...                  ...  ...          ...   ...     ...        ...
267010     United States  USA  1904 Summer  1904  Summer  St. Louis
267089           Germany  GER  1904 Summer  1904  Summer  St. Louis
267090           Germany  GER  1904 Summer  1904  Summer  St. Louis
268337            Greece  GRE  1904 Summer  1904  Summer  St. Louis
270058     United States  USA  1904 Summer  1904  Summer  St. Louis

             Sport                                              Event   Medal
711         Rowing                          Rowing Men's Coxed Eights    Gold
1449          Golf                              Golf Men's Individual     NaN
1458      Swimming                  Swimming Men's 220 yard Freestyle     NaN
1459      Swimming                  Swimming Men's 880 yard Freestyle     NaN
1460      Swimming                  Swimming Men's One Mile Freestyle     NaN
...            ...                                                ...     ...
267010  Gymnastics  Gymnastics Men's Individual All-Around, Appara...     NaN
267089    Swimming                 Swimming Men's 100 Yard Backstroke  Bronze
267090    Swimming               Swimming Men's 440 Yard Breaststroke    Gold
268337   Athletics                           Athletics Men's Marathon     NaN
270058   Wrestling             Wrestling Men's Lightweight, Freestyle  Bronze

[1301 rows x 15 columns]
1906
            ID                     Name Sex   Age  Height  Weight  \
268        139   George "Ioannis" Abbot   M   NaN     NaN     NaN
887        508         Bernhard Abraham   M   NaN     NaN     NaN
918        520  Sidney Solomon Abrahams   M  21.0     NaN     NaN
919        520  Sidney Solomon Abrahams   M  21.0     NaN     NaN
2170      1208          Ioannis Agrimis   M   NaN     NaN     NaN
...        ...                      ...  ..   ...     ...     ...
270355  135239          Khristos Zorbas   M   NaN     NaN     NaN
270356  135239          Khristos Zorbas   M   NaN     NaN     NaN
270357  135239          Khristos Zorbas   M   NaN     NaN     NaN
270358  135239          Khristos Zorbas   M   NaN     NaN     NaN
270895  135474     Albert Hermann Zrner   M  16.0     NaN     NaN

                                                   Team  NOC        Games  \
268                                       Thessalonki-1  GRE  1906 Summer
887                                             Germany  GER  1906 Summer
918                                       Great Britain  GBR  1906 Summer
919                                       Great Britain  GBR  1906 Summer
2170    Large boat, Central Naval Prep School "Poros"-1  GRE  1906 Summer
...                                                 ...  ...          ...
270355                                           Greece  GRE  1906 Summer
270356                                           Greece  GRE  1906 Summer
270357                                           Greece  GRE  1906 Summer
270358                                           Greece  GRE  1906 Summer
270895                                          Germany  GER  1906 Summer

        Year  Season    City       Sport  \
268     1906  Summer  Athina    Football
887     1906  Summer  Athina  Gymnastics
918     1906  Summer  Athina   Athletics
919     1906  Summer  Athina   Athletics
2170    1906  Summer  Athina      Rowing
...      ...     ...     ...         ...
270355  1906  Summer  Athina     Fencing
270356  1906  Summer  Athina     Fencing
270357  1906  Summer  Athina     Fencing
270358  1906  Summer  Athina     Fencing
270895  1906  Summer  Athina      Diving

                                              Event   Medal
268                         Football Men's Football  Bronze
887                Gymnastics Men's Team All-Around     NaN
918                      Athletics Men's 100 metres     NaN
919                       Athletics Men's Long Jump     NaN
2170         Rowing Men's 17-Man Naval Rowing Boats    Gold
...                                             ...     ...
270355                     Fencing Men's epee, Team     NaN
270356              Fencing Men's Sabre, Individual     NaN
270357  Fencing Men's Sabre, Individual, Three Hits     NaN
270358                    Fencing Men's Sabre, Team  Silver
270895                        Diving Men's Platform     NaN

[1733 rows x 15 columns]
1908
            ID                    Name Sex   Age  Height  Weight  \
1149       635         Alfredo Accorsi   M  27.0     NaN     NaN
1354       767  Johannes "Johann" Adam   M   NaN     NaN     NaN
1355       767  Johannes "Johann" Adam   M   NaN     NaN     NaN
1463       814            Edward Adams   M   NaN     NaN     NaN
1505       836             Platt Adams   M  23.0   188.0    78.0
...        ...                     ...  ..   ...     ...     ...
270474  135286      Kharalambos Zouras   M  23.0     NaN     NaN
270475  135286      Kharalambos Zouras   M  23.0     NaN     NaN
270750  135406           Bla Zulawszky   M  38.0     NaN     NaN
270751  135406           Bla Zulawszky   M  38.0     NaN     NaN
270896  135474    Albert Hermann Zrner   M  18.0     NaN     NaN

                 Team  NOC        Games  Year  Season    City       Sport  \
1149            Italy  ITA  1908 Summer  1908  Summer  London  Gymnastics
1354          Germany  GER  1908 Summer  1908  Summer  London     Fencing
1355          Germany  GER  1908 Summer  1908  Summer  London     Fencing
1463    Great Britain  GBR  1908 Summer  1908  Summer  London      Boxing
1505    United States  USA  1908 Summer  1908  Summer  London   Athletics
...               ...  ...          ...   ...     ...     ...         ...
270474         Greece  GRE  1908 Summer  1908  Summer  London   Athletics
270475         Greece  GRE  1908 Summer  1908  Summer  London   Athletics
270750        Hungary  HUN  1908 Summer  1908  Summer  London     Fencing
270751        Hungary  HUN  1908 Summer  1908  Summer  London     Fencing
270896        Germany  GER  1908 Summer  1908  Summer  London      Diving

                                           Event   Medal
1149            Gymnastics Men's Team All-Around     NaN
1354              Fencing Men's epee, Individual     NaN
1355             Fencing Men's Sabre, Individual     NaN
1463                  Boxing Men's Featherweight     NaN
1505          Athletics Men's Standing High Jump     NaN
...                                          ...     ...
270474             Athletics Men's Javelin Throw     NaN
270475  Athletics Men's Javelin Throw, Freestyle     NaN
270750            Fencing Men's epee, Individual     NaN
270751           Fencing Men's Sabre, Individual  Silver
270896                  Diving Men's Springboard    Gold

[3101 rows x 15 columns]
1912
            ID                  Name Sex   Age  Height  Weight     Team  NOC  \
35          15  Arvo Ossian Aaltonen   M  22.0     NaN     NaN  Finland  FIN
36          15  Arvo Ossian Aaltonen   M  22.0     NaN     NaN  Finland  FIN
95          32  Olav Augunson Aarnes   M  23.0     NaN     NaN   Norway  NOR
107         39    Lars Thorlaksn Aas   M  33.0     NaN     NaN   Norway  NOR
108         39    Lars Thorlaksn Aas   M  33.0     NaN     NaN   Norway  NOR
...        ...                   ...  ..   ...     ...     ...      ...  ...
270752  135406         Bla Zulawszky   M  42.0     NaN     NaN  Hungary  HUN
270753  135406         Bla Zulawszky   M  42.0     NaN     NaN  Hungary  HUN
270897  135474  Albert Hermann Zrner   M  22.0     NaN     NaN  Germany  GER
270898  135474  Albert Hermann Zrner   M  22.0     NaN     NaN  Germany  GER
270899  135474  Albert Hermann Zrner   M  22.0     NaN     NaN  Germany  GER

              Games  Year  Season       City      Sport  \
35      1912 Summer  1912  Summer  Stockholm   Swimming
36      1912 Summer  1912  Summer  Stockholm   Swimming
95      1912 Summer  1912  Summer  Stockholm  Athletics
107     1912 Summer  1912  Summer  Stockholm    Fencing
108     1912 Summer  1912  Summer  Stockholm    Fencing
...             ...   ...     ...        ...        ...
270752  1912 Summer  1912  Summer  Stockholm    Fencing
270753  1912 Summer  1912  Summer  Stockholm    Fencing
270897  1912 Summer  1912  Summer  Stockholm     Diving
270898  1912 Summer  1912  Summer  Stockholm     Diving
270899  1912 Summer  1912  Summer  Stockholm     Diving

                                         Event   Medal
35      Swimming Men's 200 metres Breaststroke     NaN
36      Swimming Men's 400 metres Breaststroke     NaN
95                   Athletics Men's High Jump     NaN
107             Fencing Men's Foil, Individual     NaN
108             Fencing Men's epee, Individual     NaN
...                                        ...     ...
270752          Fencing Men's Foil, Individual     NaN
270753         Fencing Men's Sabre, Individual     NaN
270897                Diving Men's Springboard     NaN
270898                   Diving Men's Platform  Silver
270899                 Diving Men's Plain High     NaN

[4040 rows x 15 columns]
1920
            ID                  Name Sex   Age  Height  Weight         Team  \
2            3   Gunnar Nielsen Aaby   M  24.0     NaN     NaN      Denmark
37          15  Arvo Ossian Aaltonen   M  30.0     NaN     NaN      Finland
38          15  Arvo Ossian Aaltonen   M  30.0     NaN     NaN      Finland
86          25      Alf Lied Aanning   M  24.0     NaN     NaN       Norway
106         38          Karl Jan Aas   M  20.0     NaN     NaN       Norway
...        ...                   ...  ..   ...     ...     ...          ...
270672  135364        Vittorio Zucca   M  24.0     NaN     NaN        Italy
270747  135405          Fritz Zulauf   M  27.0     NaN     NaN  Switzerland
270748  135405          Fritz Zulauf   M  27.0     NaN     NaN  Switzerland
270749  135405          Fritz Zulauf   M  27.0     NaN     NaN  Switzerland
270843  135455       Vjekoslav upani   M  19.0     NaN     NaN   Yugoslavia

        NOC        Games  Year  Season       City       Sport  \
2       DEN  1920 Summer  1920  Summer  Antwerpen    Football
37      FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
38      FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
86      NOR  1920 Summer  1920  Summer  Antwerpen  Gymnastics
106     NOR  1920 Summer  1920  Summer  Antwerpen  Gymnastics
...     ...          ...   ...     ...        ...         ...
270672  ITA  1920 Summer  1920  Summer  Antwerpen   Athletics
270747  SUI  1920 Summer  1920  Summer  Antwerpen    Shooting
270748  SUI  1920 Summer  1920  Summer  Antwerpen    Shooting
270749  SUI  1920 Summer  1920  Summer  Antwerpen    Shooting
270843  YUG  1920 Summer  1920  Summer  Antwerpen    Football

                                                Event   Medal
2                             Football Men's Football     NaN
37             Swimming Men's 200 metres Breaststroke  Bronze
38             Swimming Men's 400 metres Breaststroke  Bronze
86      Gymnastics Men's Team All-Around, Free System  Silver
106     Gymnastics Men's Team All-Around, Free System  Silver
...                                               ...     ...
270672           Athletics Men's 4 x 100 metres Relay     NaN
270747           Shooting Men's Military Pistol, Team  Bronze
270748    Shooting Men's Free Pistol, 50 metres, Team     NaN
270749      Shooting Men's Military Pistol, 30 metres  Bronze
270843                        Football Men's Football     NaN

[4292 rows x 15 columns]
1924
            ID                   Name Sex   Age  Height  Weight  \
39          15   Arvo Ossian Aaltonen   M  34.0     NaN     NaN
132         47   Erling Rudolf Aastad   M  26.0   177.0    74.0
152         58       Georgi Abadzhiev   M   NaN     NaN     NaN
153         58       Georgi Abadzhiev   M   NaN     NaN     NaN
181         79  Carlos Abarca Gonzlez   M  23.0     NaN     NaN
...        ...                    ...  ..   ...     ...     ...
270673  135364         Vittorio Zucca   M  28.0     NaN     NaN
270676  135366    Francesco Zucchetti   M  22.0     NaN     NaN
270794  135427      Frank Thomas Zuna   M  31.0   175.0    69.0
271010  135521          Anton Zwerina   M  23.0     NaN    66.0
271038  135539  Marius Edmund Zwiller   M  18.0     NaN     NaN

                 Team  NOC        Games  Year  Season   City          Sport  \
39            Finland  FIN  1924 Summer  1924  Summer  Paris       Swimming
132            Norway  NOR  1924 Summer  1924  Summer  Paris      Athletics
152          Bulgaria  BUL  1924 Summer  1924  Summer  Paris        Cycling
153          Bulgaria  BUL  1924 Summer  1924  Summer  Paris        Cycling
181             Chile  CHI  1924 Summer  1924  Summer  Paris         Boxing
...               ...  ...          ...   ...     ...    ...            ...
270673          Italy  ITA  1924 Summer  1924  Summer  Paris      Athletics
270676          Italy  ITA  1924 Summer  1924  Summer  Paris        Cycling
270794  United States  USA  1924 Summer  1924  Summer  Paris      Athletics
271010        Austria  AUT  1924 Summer  1924  Summer  Paris  Weightlifting
271038         France  FRA  1924 Summer  1924  Summer  Paris       Swimming

                                           Event   Medal
39        Swimming Men's 200 metres Breaststroke     NaN
132                    Athletics Men's Long Jump     NaN
152          Cycling Men's Road Race, Individual     NaN
153                Cycling Men's Road Race, Team     NaN
181                   Boxing Men's Featherweight     NaN
...                                          ...     ...
270673                Athletics Men's 100 metres     NaN
270676  Cycling Men's Team Pursuit, 4,000 metres    Gold

### Challenges 1

List our Olympics Dataframe
list only the NOC columns using both the [" "] and dot notation
Name the type of object for the above 
list the edition, city name and medal column 
what is the type of the object

In [19]:
import pandas as pd

In [20]:
oo = pd.read_csv("athlete_events.csv")
oo.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [21]:
oo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [22]:
oo["NOC"]

0         CHN
1         CHN
2         DEN
3         DEN
4         NED
         ...
271111    POL
271112    POL
271113    POL
271114    POL
271115    POL
Name: NOC, Length: 271116, dtype: object

In [23]:
oo.NOC

0         CHN
1         CHN
2         DEN
3         DEN
4         NED
         ...
271111    POL
271112    POL
271113    POL
271114    POL
271115    POL
Name: NOC, Length: 271116, dtype: object

In [24]:
type(oo.NOC)

pandas.core.series.Series

In [25]:
oo[["Name","City","Year","Medal"]]

                            Name            City  Year Medal
0                      A Dijiang       Barcelona  1992   NaN
1                       A Lamusi          London  2012   NaN
2            Gunnar Nielsen Aaby       Antwerpen  1920   NaN
3           Edgar Lindenau Aabye           Paris  1900  Gold
4       Christine Jacoba Aaftink         Calgary  1988   NaN
...                          ...             ...   ...   ...
271111                Andrzej ya       Innsbruck  1976   NaN
271112                  Piotr ya           Sochi  2014   NaN
271113                  Piotr ya           Sochi  2014   NaN
271114        Tomasz Ireneusz ya          Nagano  1998   NaN
271115        Tomasz Ireneusz ya  Salt Lake City  2002   NaN

[271116 rows x 4 columns]

### Challenges 3

In which event did Piotr ya win a medal 
which country has won the most men's gold medal in single badminton over the years
Display the male gold medal winner for the 100m track and field sprint event over the years 

List the results starting with most recent 

show the olympic city , edition, athlete and the country  they represented

In [26]:
# In which event did Jesse Owens win a medal

In [33]:
py=oo[oo.Name == "Piotr ya"]

In [53]:
py.Event.value_counts()

Ski Jumping Men's Large Hill, Individual    1
Ski Jumping Men's Large Hill, Team          1
Name: Event, dtype: int64

In [54]:
#which country has won the most men's gold medal in single badminton over the years

In [55]:
gbm = oo[(oo.Medal == "Gold") & (oo.Sex == "M") & (oo.Sport == "Badminton")]

In [56]:
gbm.sort_values(by="Name")

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
31409,16152,Alexander Alan Budikusuma Wiratama,M,24.0,178.0,71.0,Indonesia,INA,1992 Summer,1992,Summer,Barcelona,Badminton,Badminton Men's Singles,Gold
33538,17299,Cai Yun,M,32.0,181.0,68.0,China-1,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Doubles,Gold
260443,130336,Candra Wijaya,M,24.0,173.0,67.0,Indonesia,INA,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Men's Doubles,Gold
39337,20238,Chen Long,M,27.0,188.0,81.0,China,CHN,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Men's Singles,Gold
73578,37396,Fu Haifeng,M,28.0,181.0,78.0,China-1,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Doubles,Gold
73579,37396,Fu Haifeng,M,32.0,181.0,78.0,China-1,CHN,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Men's Doubles,Gold
87648,44426,Ha Tae-Gwon,M,29.0,187.0,87.0,South Korea-2,KOR,2004 Summer,2004,Summer,Athina,Badminton,Badminton Men's Doubles,Gold
216957,108952,Hendra Setiawan,M,23.0,183.0,82.0,Indonesia-1,INA,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Men's Doubles,Gold
108331,54755,Ji Xinpeng,M,22.0,181.0,70.0,China,CHN,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Men's Singles,Gold
118307,59848,Kim Dong-Mun,M,20.0,184.0,74.0,South Korea-1,KOR,1996 Summer,1996,Summer,Atlanta,Badminton,Badminton Mixed Doubles,Gold
118312,59848,Kim Dong-Mun,M,28.0,184.0,74.0,South Korea-2,KOR,2004 Summer,2004,Summer,Athina,Badminton,Badminton Men's Doubles,Gold
118853,60159,Kim Mun-Su,M,28.0,179.0,NaN,South Korea-1,KOR,1992 Summer,1992,Summer,Barcelona,Badminton,Badminton Men's Doubles,Gold
135564,68209,Lee Yong-Dae,M,19.0,180.0,74.0,South Korea-1,KOR,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Mixed Doubles,Gold
139311,69968,Lin Dan,M,24.0,177.0,70.0,China,CHN,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Men's Singles,Gold
139312,69968,Lin Dan,M,28.0,177.0,70.0,China,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Singles,Gold
117719,59576,Markis Kido,M,23.0,165.0,62.0,Indonesia-1,INA,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Men's Doubles,Gold
182154,91558,Park Ju-Bong,M,27.0,182.0,68.0,South Korea-1,KOR,1992 Summer,1992,Summer,Barcelona,Badminton,Badminton Men's Doubles,Gold
99666,50431,Poul-Erik Hyer Larsen (-Engel Hyer),M,30.0,188.0,79.0,Denmark,DEN,1996 Summer,1996,Summer,Atlanta,Badminton,Badminton Men's Singles,Gold
146785,73674,Rexy Ronald Mainaky,M,28.0,170.0,65.0,Indonesia,INA,1996 Summer,1996,Summer,Atlanta,Badminton,Badminton Men's Doubles,Gold
231426,116120,Ricky Achmad Subagja,M,25.0,172.0,62.0,Indonesia,INA,1996 Summer,1996,Summer,Atlanta,Badminton,Badminton Men's Doubles,Gold
95679,48435,Taufik Hidayat,M,23.0,175.0,65.0,Indonesia,INA,2004 Summer,2004,Summer,Athina,Badminton,Badminton Men's Singles,Gold
2453,1374,Tontowi Ahmad,M,29.0,179.0,72.0,Indonesia-1,INA,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Mixed Doubles,Gold
86511,43865,Tony Gunawan,M,25.0,173.0,80.0,Indonesia,INA,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Men's Doubles,Gold
268814,134490,Zhang Jun,M,22.0,175.0,75.0,China-2,CHN,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Mixed Doubles,Gold
268815,134490,Zhang Jun,M,26.0,175.0,75.0,China-2,CHN,2004 Summer,2004,Summer,Athina,Badminton,Badminton Mixed Doubles,Gold
268871,134523,Zhang Nan,M,22.0,183.0,75.0,China-1,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Mixed Doubles,Gold
268873,134523,Zhang Nan,M,26.0,183.0,75.0,China-1,CHN,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Men's Doubles,Gold

In [57]:
#Which 3 countries have won the most medals in recent years

In [60]:
rec = oo[oo.Year>= 1984]
rec.NOC.value_counts().head(3)

USA    9096
CAN    5960
GER    5688
Name: NOC, dtype: int64

In [61]:
#Display the male gold medal winner for the 100m track and field sprint event over the years

In [ ]:
gmh = oo[(oo.Sex == "M") & (oo.Medal == "Gold") & (oo.Event == )]